version: "3.3"

services:
  pg-client_production:
    container_name: pg-client_production
    # build: .
    image: ${CLIENT_IMAGE}
    expose:
      - 80
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      VIRTUAL_PORT: ${CLIENT_VIRTUAL_PORT}
      VIRTUAL_HOST: ${PRODUCTION_CLIENT_DOMAIN}
      LETSENCRYPT_HOST: ${PRODUCTION_CLIENT_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      DEV_GRAPHQL_ENDPOINT: ${NEXT_PUBLIC_DEVELOPMENT_GQL_URI}
      PROD_GRAPHQL_ENDPOINT: ${NEXT_PUBLIC_PRODUCTION_GQL_URI}
      PROD_WEBSOCKET_URL: ${NEXT_PUBLIC_PRODUCTION_WEBSOCKET_URL}
      DEV_WEBSOCKET_URL: ${NEXT_PUBLIC_DEVELOPMENT_WEBSOCKET_URL}
      GRAPHQL_PORT: ${GRAPHQL_PORT}

      PRODUCTION_CLIENT_DOMAIN: ${PRODUCTION_CLIENT_DOMAIN}
      PRODUCTION_API_DOMAIN: ${PRODUCTION_API_DOMAIN}
      STAGING_API_DOMAIN: ${STAGING_API_DOMAIN}

      CLIENT_IMAGE: ${CLIENT_IMAGE}
      CLIENT_VIRTUAL_PORT: ${CLIENT_VIRTUAL_PORT}

networks:
  default:
    external:
      name: ${NETWORK}
